language: node_js
node_js:
  - "lts/*"
addons:
  ssh_known_hosts: fromnoobstogeeks.com
before_install:
- npm config set strict-ssl false
- npm install -g hexo-cli
- wget https://github.com/jgm/pandoc/releases/download/2.3/pandoc-2.3-1-amd64.deb && sudo dpkg -i pandoc-2.3-1-amd64.deb
- openssl aes-256-cbc -K $encrypted_936f9aa5c77b_key -iv $encrypted_936f9aa5c77b_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: npm install && hexo generate --deploy && scp -r $TRAVIS_BUILD_DIR/public/* blog@fromnoobstogeeks.com:/home/blog/web/fromnoobstogeeks
  on:
    branch: develop
