language: generic
addons:
  ssh_known_hosts: mystories.vn
before_install:
- openssl aes-256-cbc -K $encrypted_936f9aa5c77b_key -iv $encrypted_936f9aa5c77b_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: scp -r $TRAVIS_BUILD_DIR/* hoangnm@mystories.vn:/home/hoangnm/web/fromnoobstogeeks/html
  on:
    branch: master
