language: generic
addons:
  ssh_known_hosts: fromnoobstogeeks.com
before_install:
- sudo apt-get install -y nodejs-legacy npm --no-install-recommends
- sudo npm config set strict-ssl false
- sudo npm install -g hexo
- openssl aes-256-cbc -K $encrypted_936f9aa5c77b_key -iv $encrypted_936f9aa5c77b_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: npm install && hexo generate --deploy && scp -r $TRAVIS_BUILD_DIR/public/* hoangnm@fromnoobstogeeks.com:/home/hoangnm/web/fromnoobstogeeks/html
  on:
    branch: develop
