menu:
    Blog: /
    Archive: /archives/
    About: /about/
    GitHub: https://github.com/khanhtc1202
    Rss: /atom.xml

favicon: /images/larry-hi.png
logo: /images/larry-hi.png

# Comment
# e.g disqus: seansun
disqus: fromnoobstogeeks

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2017

language: en
